# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`
# Borrowed and inspired by: https://github.com/mathiasbynens/dotfiles/blob/master/Brewfile

# Make sure we're using the latest Homebrew
brew update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
# Install some other useful utilities like `sponge`
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`
brew install gnu-sed --with-default-names
# Install Bash 4
# Note: don't forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
brew install bash
brew install bash-completion

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/screen

# Fix php install quirk
#tap homebrew/dupes
#update
#upgrade

#tap homebrew/dupes

#install homebrew/php/php55 --with-gmp

# Macvim
# install macvim # Standard brew vim installation already installs this

# Install other useful binaries
brew install ack
brew install git
brew install nmap
brew install tree
brew install ngrep
brew install ragel

# Install GNU stow
brew install stow

# Install android sdks
brew install android-sdk
brew install android-ndk

# Make, compilers, and heavier etilities
brew install cmake
brew install gcc

brew install zlib
brew install ffmpeg
brew install openssl
brew install wireshark
brew install tmux

# You may need this for powerline
# See: http://superuser.com/questions/762345/powerline-patched-fonts-on-osx-10-9-3-iterm2-chrome
# and: https://github.com/Lokaltog/powerline-fonts
brew install fontforge --with-python

# Databases
brew install sqlite
brew install mysql
brew install redis

# Python Qt
brew install qt
brew install sip
brew install pyqt

#tmate
brew update
brew tap nviennot/tmate
brew install tmate

# Node nvm
brew install nvm

# Python pyenv
brew install pyenv

# RVM needs to be installed directly

# Install Brew Cask
brew install cask

# Remove outdated versions from the cellar
brew cleanup
